version: 2.1

orbs:
  omniauth-gusto:
    executors:
      ruby:
        docker:
          - image: circleci/ruby:2.6.0-node-browsers

    commands:
      install:
        steps:
          - checkout
          - run:
              name: Configure Bundler
              command: |
                echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
                source $BASH_ENV
                gem install bundler
          # Download and cache dependencies
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "Gemfile.lock" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
          - run:
              name: install dependencies
              command: |
                bundle install --jobs=4 --retry=3 --path vendor/bundle
          - save_cache:
              paths:
                - ./vendor/bundle
              key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    jobs:
      test:
        executor: ruby
        steps:
          - install
          - run:
              name: run tests
              command: |
                mkdir /tmp/test-results
                TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
                  circleci tests split --split-by=timings)"

                bundle exec rspec \
                  --format progress \
                  --format RspecJunitFormatter \
                  --out /tmp/test-results/rspec.xml \
                  --format progress \
                  $TEST_FILES
          - store_test_results:
              path: /tmp/test-results
          - store_artifacts:
              path: /tmp/test-results
              destination: test-results

      lint:
        executor: ruby
        steps:
          - install
          - run:
              name: lint
              command: bundle exec rubocop

      publish:
        executor: ruby
        steps:
          - echo 'Publishing'

workflows:
  version: 2
  CI:
    jobs:
      - omniauth-gusto/test:
          name: test
      - omniauth-gusto/lint:
          name: lint
      - omniauth-gusto/publish:
          name: publish
          requires:
            - test
            - lint
