version: 2.1

orbs:
  gusto: gusto/gusto@0.0.9
  omniauth-gusto:
    orbs:
      gusto: gusto/gusto@0.0.9

    jobs:
      test:
        executor: << parameters.executor >>
        parameters:
          executor:
            type: executor
        steps:
          - gusto/bundle-install
          - run:
              name: run tests
              command: |
                mkdir /tmp/test-results
                TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
                  circleci tests split --split-by=timings)"

                bundle exec rspec \
                  --format progress \
                  --format RspecJunitFormatter \
                  --out /tmp/test-results/rspec.xml \
                  --format progress \
                  $TEST_FILES
          - store_test_results:
              path: /tmp/test-results
          - store_artifacts:
              path: /tmp/test-results
              destination: test-results

      build:
        executor: << parameters.executor >>
        parameters:
          executor:
            type: string
        steps:
          - gusto/bundle-install
          - run: gem build omniauth-gusto.gemspec

      publish:
        executor: gusto/ruby-2-6
        steps:
          - run: echo 'Publishing'

workflows:
  version: 2
  CI:
    jobs:
      - omniauth-gusto/test:
          name: test (Ruby 2.3)
          executor: gusto/ruby-2-3
      - omniauth-gusto/test:
          name: test (Ruby 2.4)
          executor: gusto/ruby-2-4
      - omniauth-gusto/test:
          name: test (Ruby 2.5)
          executor: gusto/ruby-2-5
      - omniauth-gusto/test:
          name: test (Ruby 2.6)
          executor: gusto/ruby-2-6
      - gusto/ruby-lint:
          name: lint
      - omniauth-gusto/build:
          name: build (Ruby 2.3)
          executor: gusto/ruby-2-3
      - omniauth-gusto/build:
          name: build (Ruby 2.4)
          executor: gusto/ruby-2-4
      - omniauth-gusto/build:
          name: build (Ruby 2.5)
          executor: gusto/ruby-2-5
      - omniauth-gusto/build:
          name: build (Ruby 2.6)
          executor: gusto/ruby-2-6
      - omniauth-gusto/publish:
          name: publish
          requires:
            - test (Ruby 2.3)
            - test (Ruby 2.4)
            - test (Ruby 2.5)
            - test (Ruby 2.6)
            - lint
            - build (Ruby 2.3)
            - build (Ruby 2.4)
            - build (Ruby 2.5)
            - build (Ruby 2.6)
